// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ismission6ISGANG.Models;

namespace ismission6ISGANG.Migrations
{
    [DbContext(typeof(TasksContext))]
    partial class TasksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("ismission6ISGANG.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("ismission6ISGANG.Models.Tasks", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            CategoryId = 1,
                            Completed = false,
                            Date = "03/12/22",
                            Quadrant = 1,
                            Task = "Crises"
                        },
                        new
                        {
                            TaskID = 2,
                            CategoryId = 2,
                            Completed = false,
                            Date = "04/15/22",
                            Quadrant = 2,
                            Task = "Relationship Building"
                        },
                        new
                        {
                            TaskID = 3,
                            CategoryId = 3,
                            Completed = false,
                            Date = "2/28/22",
                            Quadrant = 3,
                            Task = "Interruptions"
                        },
                        new
                        {
                            TaskID = 4,
                            CategoryId = 3,
                            Completed = true,
                            Date = "04/01/22",
                            Quadrant = 4,
                            Task = "Some Phone Work"
                        });
                });

            modelBuilder.Entity("ismission6ISGANG.Models.Tasks", b =>
                {
                    b.HasOne("ismission6ISGANG.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
